I'm sorry, but an uncaught exception occurred.

While running game code:
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\thien\\AppData\\Roaming/RenPy/visualNoveldraft1-1739834055\\persistent'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "D:\renpy\renpy-8.3.4-sdk\renpy\bootstrap.py", line 359, in bootstrap
    renpy.main.main()
  File "D:\renpy\renpy-8.3.4-sdk\renpy\main.py", line 666, in main
    renpy.persistent.update(True)
  File "D:\renpy\renpy-8.3.4-sdk\renpy\persistent.py", line 434, in update
    save()
  File "D:\renpy\renpy-8.3.4-sdk\renpy\persistent.py", line 456, in save
    renpy.loadsave.location.save_persistent(compressed)
  File "D:\renpy\renpy-8.3.4-sdk\renpy\savelocation.py", line 622, in save_persistent
    l.save_persistent(data)
  File "D:\renpy\renpy-8.3.4-sdk\renpy\savelocation.py", line 430, in save_persistent
    safe_rename(fn_new, fn)
  File "D:\renpy\renpy-8.3.4-sdk\renpy\loadsave.py", line 303, in safe_rename
    os.unlink(new)
PermissionError: [WinError 5] Access is denied: 'C:\\Users\\thien\\AppData\\Roaming/RenPy/visualNoveldraft1-1739834055\\persistent'

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.4.24120703
visualNoveldraft1 1.0
Wed Feb 19 22:33:12 2025
